name       : haskell-base-prelude
version    : '1.3'
release    : 2
source     :
    - https://hackage.haskell.org/package/base-prelude-1.3/base-prelude-1.3.tar.gz : e3cc66e99d6c83aac548c4d8e6a166e5bd9cf557947cde49161026d0341267fe
license    : MIT
component  : programming.haskell
summary    : The most complete prelude formed solely from the "base" package
description: |
    The most complete prelude formed solely from the "base" package
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
