name       : haskell-base-prelude
version    : 1.2.1
release    : 1
source     :
    - http://hackage.haskell.org/package/base-prelude-1.2.1/base-prelude-1.2.1.tar.gz : 07f30ca0f620ce67dbd07f82793fe2de69492b6df7445c5676ec7e5288139ab8
license    : MIT
component  : programming.haskell
summary    : The most complete prelude formed solely from the "base" package
description: |
    The most complete prelude formed solely from the "base" package
builddeps  :
    - ghc
    - haskell-cabal-install
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
